services:
  jekyll:
    image: jekyll/jekyll:4
    working_dir: /srv/jekyll
    command: sh -c "bundle install && bundle exec jekyll serve --watch --host ${JEKYLL_BIND_HOST:-0.0.0.0} --livereload --force_polling"
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1}
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
      no_proxy: ${no_proxy:-localhost,127.0.0.1}
    ports:
      - '${JEKYLL_PUBLISH_IP:-127.0.0.1}:${JEKYLL_PORT:-4000}:4000'
      - '${JEKYLL_PUBLISH_IP:-127.0.0.1}:${LIVERELOAD_PORT:-35729}:35729'
    volumes:
      - .:/srv/jekyll
  tailwind:
    image: node:22
    working_dir: /srv/jekyll
    volumes:
      - .:/srv/jekyll
    command: npm run build:css:prod:watch
#    command: npx postcss assets/css/tailwind.css -o assets/css/style.css --watch
